### ISSUE TITLE
Question on Tables 5 and 6

### ISSUE THREAD

**Issue by NebiyouTen** [soominkwon/resample#1]
Hello, 

Thank you for your great work and for sharing your code. I'm trying to reproduce the results in Table 5 and 6 for the FFHQ dataset. Specifically, I'm working on Gaussian Deblurring using the default settings provided as:

```python3 sample_condition.py  --task_config configs/tasks/gaussian_deblur_config.yaml ```

I obtained slightly lower results for both your method (e.g., 1 dB less in PSNR) and DPS (e.g., 0.5 dB less in PSNR). Should I adjust the hyperparameters to improve them?

In addition, you mentioned that you sampled 100 images from both the FFHQ and CelebA-HQ validation datasets. Is it possible to share which samples were used?

Thanks,

**Comment by soominkwon** [comment]
Hi,

Sorry for the late response. Unfortunately, I do not have saved the 100 images I used from the validation datasets. I would believe that you could sub-sample some yourself and the performance should be similar.

As for tuning the hyperparameters -- yes I would suggest you tune a bit for the best performance as stated in our paper. Perhaps you can use those values first and see how close the results are.
